## Spam classification using NB

In [2]:
import matplotlib.pyplot as plt
import nltk
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.utils.multiclass import unique_labels



In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/AiDevNepal/ai-saturdays-workshop-8/master/data/spam.csv')

data['target'] = np.where(data['target']=='spam',1, 0)
data.head(10)



text  target
0  Go until jurong point, crazy.. Available only ...       0
1                      Ok lar... Joking wif u oni...       0
2  Free entry in 2 a wkly comp to win FA Cup fina...       1
3  U dun say so early hor... U c already then say...       0
4  Nah I don't think he goes to usf, he lives aro...       0
5  FreeMsg Hey there darling it's been 3 week's n...       1
6  Even my brother is not like to speak with me. ...       0
7  As per your request 'Melle Melle (Oru Minnamin...       0
8  WINNER!! As a valued network customer you have...       1
9  Had your mobile 11 months or more? U R entitle...       1

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(data['text'],
                                                    data['target'],
                                                    random_state=0)


In [6]:
# extract features
vectorizer = CountVectorizer(ngram_range=(1, 2)).fit(X_train)
X_train_vectorized = vectorizer.transform(X_train)
X_train_vectorized.toarray().shape


(4179, 40704)

In [8]:
model = MultinomialNB(alpha=0.1)
model.fit(X_train_vectorized, Y_train)
predictions = model.predict(vectorizer.transform(X_test))
print("Accuracy:", 100 * sum(predictions == Y_test) / len(predictions), '%')

Accuracy: 98.99497487437186 %


In [9]:
model.predict(vectorizer.transform(
    [
        "Thank you, ABC. Can you also share your LinkedIn profile? As you are a good at programming at pyhthon, would be willing to see your personal/college projects.",
        "Hi y’all, We have a Job Openings in the positions of software engineer, IT officer at ABC Company.Kindly, send us your resume and the cover letter as soon as possible if you think you are an eligible candidate and meet the criteria.",
        "Dear ABC, Congratulations! You have been selected as a SOftware Developer at XYZ Company. We were really happy to see your enthusiasm for this vision and mission. We are impressed with your background and we think you would make an excellent addition to the team.",
    ])
            )

array([0, 0, 0])

In [10]:
model.predict(vectorizer.transform(
    [
        "congratulations, you became today's lucky winner",
        "1-month unlimited calls offer Activate now",
        "Ram wants your phone number",

    ])
            )

array([1, 1, 1])

## Sentiment analysis using SVM

In [11]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import matplotlib.pyplot as plt
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
import pickle
import time
import re

In [13]:
train_set = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/Corona_NLP_train.csv',encoding="latin1")
test_set = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/Corona_NLP_test.csv',encoding="latin1")

train_set.head()

UserName  ScreenName   Location     TweetAt  \
0      3799       48751     London  16-03-2020   
1      3800       48752         UK  16-03-2020   
2      3801       48753  Vagabonds  16-03-2020   
3      3802       48754        NaN  16-03-2020   
4      3803       48755        NaN  16-03-2020   

                                       OriginalTweet           Sentiment  
0  @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral  
1  advice Talk to your neighbours family to excha...            Positive  
2  Coronavirus Australia: Woolworths to give elde...            Positive  
3  My food stock is not the only one which is emp...            Positive  
4  Me, ready to go at supermarket during the #COV...  Extremely Negative

In [14]:
unrelevant_features = ["UserName","ScreenName","Location","TweetAt"]

train_set.drop(unrelevant_features,inplace=True,axis=1)
test_set.drop(unrelevant_features,inplace=True,axis=1)
train_set.head()

OriginalTweet           Sentiment
0  @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral
1  advice Talk to your neighbours family to excha...            Positive
2  Coronavirus Australia: Woolworths to give elde...            Positive
3  My food stock is not the only one which is emp...            Positive
4  Me, ready to go at supermarket during the #COV...  Extremely Negative

In [15]:
train_set["Sentiment"].value_counts()

Sentiment
Positive              11422
Negative               9917
Neutral                7713
Extremely Positive     6624
Extremely Negative     5481
Name: count, dtype: int64

In [16]:
positives = train_set[(train_set["Sentiment"] == "Positive") | (train_set["Sentiment"] == "Extremely Positive")]
positives_test = test_set[(test_set["Sentiment"] == "Positive") | (test_set["Sentiment"] == "Extremely Positive")]
print(positives["Sentiment"].value_counts())
positives.head()

Sentiment
Positive              11422
Extremely Positive     6624
Name: count, dtype: int64


OriginalTweet Sentiment
1  advice Talk to your neighbours family to excha...  Positive
2  Coronavirus Australia: Woolworths to give elde...  Positive
3  My food stock is not the only one which is emp...  Positive
5  As news of the region’s first confirmed COVID...  Positive
6  Cashier at grocery store was sharing his insig...  Positive

In [17]:
negatives = train_set[(train_set["Sentiment"] == "Negative") | (train_set["Sentiment"] == "Extremely Negative")]
negatives_test = test_set[(test_set["Sentiment"] == "Negative") | (test_set["Sentiment"] == "Extremely Negative")]
print(negatives["Sentiment"].value_counts())
negatives.head()

Sentiment
Negative              9917
Extremely Negative    5481
Name: count, dtype: int64


OriginalTweet           Sentiment
4   Me, ready to go at supermarket during the #COV...  Extremely Negative
9   For corona prevention,we should stop to buy th...            Negative
20  with 100  nations inficted with  covid  19  th...  Extremely Negative
24  @10DowningStreet @grantshapps what is being do...            Negative
26  In preparation for higher demand and a potenti...            Negative

In [18]:
neutrals = train_set[train_set["Sentiment"] == "Neutral"]
neutrals_test = test_set[test_set["Sentiment"] == "Neutral"]
print(neutrals["Sentiment"].value_counts())
neutrals.head()

Sentiment
Neutral    7713
Name: count, dtype: int64


OriginalTweet Sentiment
0   @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...   Neutral
7   Was at the supermarket today. Didn't buy toile...   Neutral
10  All month there hasn't been crowding in the su...   Neutral
16  ????? ????? ????? ????? ??\r\r\n?????? ????? ?...   Neutral
17  @eyeonthearctic 16MAR20 Russia consumer survei...   Neutral

In [19]:
import warnings as wrn
wrn.filterwarnings('ignore')

negatives["Sentiment"] = 0
negatives_test["Sentiment"] = 0

positives["Sentiment"] = 2
positives_test["Sentiment"] = 2

neutrals["Sentiment"] = 1
neutrals_test["Sentiment"] = 1

negatives.head()

OriginalTweet  Sentiment
4   Me, ready to go at supermarket during the #COV...          0
9   For corona prevention,we should stop to buy th...          0
20  with 100  nations inficted with  covid  19  th...          0
24  @10DowningStreet @grantshapps what is being do...          0
26  In preparation for higher demand and a potenti...          0

In [20]:
data = pd.concat([positives,
                  positives_test,
                  neutrals,
                  neutrals_test,
                  negatives,
                  negatives_test
                 ],axis=0)

data.reset_index(inplace=True)

In [21]:
import random
for i in range(1,10):
    random_ind = random.randint(0,len(data))
    print(str(data["OriginalTweet"][random_ind]),end="\nLabel: ")
    print(str(data["Sentiment"][random_ind]),end="\n\n")

I'm just worried about all the poor people that are gonna be left eating toilet roll when they realise they didn't stock up on any fucking food #Covid_19 #CoronavirusPandemic
Label: 0







#CeemiAgency #smallbusinesssupport #coronavirus2020 #coronavirus https://t.co/Ri4cd2RdpS
Label: 0

It’s critical that during the #COVID19Aus health crisis people stay connected to essential services such as housing, electricity, water and phones. More than 60 community orgs are calling for governments and companies to make sure people #KeepConnected. https://t.co/3GBBDpdjat https://t.co/9PA9HCmxte
Label: 0


#COVID?19 #Coronavirus https://t.co/aLr6VjlO87
Label: 0

has warned people hiking prices of food He says he will send spies to town and you ll get your licences canceled Uganda produces its own food what has then led to the hiking of prices 19
Label: 0

@PippaBird @JuliaHB1 #Coronavirus isn't over, until is,we don't know the final total, my opinion is that it isn't as easily caught in public p

In [22]:
cleanedData = []

lemma = WordNetLemmatizer()
swords = stopwords.words("english")
for text in data["OriginalTweet"]:

    # Cleaning links
    text = re.sub(r'http\S+', '', text)

    # Cleaning everything except alphabetical and numerical characters
    text = re.sub("[^a-zA-Z0-9]"," ",text)

    # Tokenizing and lemmatizing
    text = nltk.word_tokenize(text.lower())
    text = [lemma.lemmatize(word) for word in text]

    # Removing stopwords
    text = [word for word in text if word not in swords]

    # Joining
    text = " ".join(text)

    cleanedData.append(text)

In [23]:
for i in range(0,5):
    print(cleanedData[i],end="\n\n")

advice talk neighbour family exchange phone number create contact list phone number neighbour school employer chemist gp set online shopping account po adequate supply regular med order

coronavirus australia woolworth give elderly disabled dedicated shopping hour amid covid 19 outbreak

food stock one empty please panic enough food everyone take need stay calm stay safe covid19france covid 19 covid19 coronavirus confinement confinementotal confinementgeneral

news region first confirmed covid 19 case came sullivan county last week people flocked area store purchase cleaning supply hand sanitizer food toilet paper good tim dodson report

cashier grocery store wa sharing insight covid 19 prove credibility commented civics class know talking



In [24]:
vectorizer = CountVectorizer(max_features=10000)
BOW = vectorizer.fit_transform(cleanedData)

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(BOW,np.asarray(data["Sentiment"]))

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(33716, 10000)
(11239, 10000)
(33716,)
(11239,)


In [26]:
from sklearn.svm import SVC
start_time = time.time()

model = SVC()
model.fit(x_train,y_train)

end_time = time.time()
process_time = round(end_time-start_time,2)
print("Fitting SVC took {} seconds".format(process_time))

Fitting SVC took 790.69 seconds


In [27]:
predictions = model.predict(x_test)

In [47]:
vocab = vectorizer.get_feature_names_out()
for sample in x_test:
    words = [vocab[i] for i in sample.nonzero()[1]]
    reconstructed_text = " ".join(words)
print(reconstructed_text)
## print(i)
y_test[i]

supply covid 19 food empty thank way supermarket think shelf many concern address reason concerned efficient method fastest dig easiest charles


2

In [50]:
np.asarray(data["Sentiment"])

array([2, 2, 2, ..., 0, 0, 0])

In [39]:
from sklearn.metrics import accuracy_score,confusion_matrix

print("Accuracy of model is {}%".format(accuracy_score(y_test,predictions) * 100))

Accuracy of model is 77.92508230269597%
